### ISSUE TITLE
Nonce too low on fresh install

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#1081]
User reports getting "nonce too low" error when sending from a fresh install

**Comment by kumavis** [comment]
@ColinLeath Hmm interesting. You have this issue every time you use metamask or only in a certain case?

**Comment by ColinLeath** [comment]
I'll try again in a while. I've just been trying to use the mkr.market
exchange. Last night I got stuck at increasing my allowance. This morning
increasing the allowance worked, but trying to add a buy order led to the
error I mentioned.

On Feb 2, 2017 12:37 PM, "kumavis" <notifications@github.com> wrote:

@ColinLeath <https://github.com/ColinLeath> Hmm interesting. You have this
issue every time you use metamask or only in a certain case?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-plugin/issues/1081#issuecomment-277075985>,
or mute the thread

**Comment by ColinLeath** [comment]
I'm now using metamask on galliumOS (linux for chromebooks). I was able to
place an order at mkr.market yesterday. As well as make a transation at
etherplay. All this with the same account I was using before.

**Comment by kumavis** [comment]
If this issue comes up again let us know : )

**Comment by dskvr** [comment]
This issue appears in MetaMask if using a loose address that has recently been used in another wallet.

How to replicate
1. Generate wallet on MEW
2. Load loose wallet into MM
3. Send a tx from MM _shouldn't have any problems_
4. Load wallet into MEW and send a tx _shouldn't have any issues_
5. Go back to MM and try to send tx _I've been able to replicate this issue with consistency, you should get "nonce too low" error_

**Comment by dskvr** [comment]
One of your team members is a jerk. Seriously? Booted from slack because I correctly his ignorance on constant functions. Shows the competence of this team...

**Comment by kumavis** [comment]
@dskvr metamask doesnt currently handle the same priv key being used in multiple places, requires a restart. we've done some refactoring recently that will make solving that problem easier. expect to see that soon.

**Comment by kumavis** [comment]
@dskvr Also im team lead and I'll happily boot anyone from the slack thats being a dick!

**Comment by kumavis** [comment]
here is the eos dapp making hundreds of requests (per user) to load data for a table
in potato gif quality

![eos-spam](https://user-images.githubusercontent.com/1474978/27841829-4a0a4ac2-60b9-11e7-9aa5-25393c9e3052.gif)

**Comment by dskvr** [comment]
@kumavis To be fair, I was responding to you being a dick. Also, was I wrong that reading constant functions don't stress the blockchain, they stress the node? I digress, it's your house, so fair enough. Even if my intent on visiting was to discourage people from spamming the channel with things that had nothing to do with MetaMask. Yeah, I saw that, looks like poor high level design. On the low level, they have constant functions they were using as getters for mapped values in the contract in order to illustrate their contract details. With 341 rows and two requests per row, that's a bit much. Instead, they should have done those details server-side with a refresh, and then left MetaMask to signing, etc.

**Comment by flyswatter** [comment]
Hey @dskvr I was on the side of your debate, and the original thing that made the conversation sound off is that you blamed Ethereum's tx throughput for the EOS bomb, which definitely gave a wrong impression of your level of understanding (given that now I've seen you answered all kinds of similar questions for other users).

I think we've all been doing a ridiculous amount of user support, and so we've had to get a little quicker at filtering out rude users. Once we smooth through this EOS issue, I wouldn't mind seeing some reconciliation if people can manage to be kind again.

**Comment by dskvr** [comment]
Understood. I was being needlessly defensive as result of what I believe to be emotional low point in my recent history. I can understand kicks, I've dealt with hundred's of trolls over the last couple weeks, in fact pretty sure it has taken a toll on my communicative abilities. In the grand scheme of things, we're all on the same team.

**Comment by kumavis** [comment]
@dskvr you can recreate your account on metamask slack if you'd like

**Comment by step21** [comment]
Sorry to resurrect this, but I have this on an old account imported into metamask, that hasn't been used in quite a while. It was only recently 'looked at' to check if there was anything on it, but the last transaction was over a year ago.
Can provide etherscan link and update if it should fix itself in a while.
