### ISSUE TITLE
Bug with eth.sign() - metamask 3.2.1 and ethereumjs-util 5.1.0

### ISSUE THREAD

**Issue by chafey** [MetaMask/metamask-plugin#1104]
I am getting inconsistent digital signature verification behavior depending upon the input message:

```javascript
function checkSig(message) {
  var address = web3.eth.accounts[0];
  var msgHex = web3.sha3(message);
  web3.eth.sign(address, msgHex, function(err, signature) {

    var sgn = signature;
    var r = eutil.toBuffer(sgn.slice(0,66));
    var s = eutil.toBuffer('0x' + sgn.slice(66,130));
    var v = parseInt(sgn.slice(130,132)) + 27;
    var msgBuffer = eutil.toBuffer(msgHex)
    var msgHash = eutil.hashPersonalMessage(msgBuffer)
    var pub = eutil.ecrecover(msgHash, v, r, s);
    var adr = '0x' + eutil.pubToAddress(pub).toString('hex');
    if(adr !== address) {
      console.log('signature check FAILED');
    } else {
      console.log('signature check succeess');
    }
  });
}

function test() {
  checkSig("Please click 'sign' to login: Y"); // fails
  checkSig("Please click 'sign' to login: Z"); // success
}

```

**Comment by chafey** [comment]
This bug still exists with 3.2.2 - not sure if it is in metamask or ethutils - will update later today when I narrow it down

**Comment by chafey** [comment]
Update: the same message will succeed with one account and fail with another

**Comment by flyswatter** [comment]
@chafey 

Ideal reproduction data would include:
Sample input message
Private key for account signing fails with.
Desired output message.

If you have an account you can sacrifice for this test that would be very helpful.

Otherwise, I just hope it's easy to reproduce, will give this serious attention tomorrow morning.

(Sorry for the delay, this is a critical bug, but it just overlapped with the end of the hackathon week we'd hosted. Next time no big releases during hackathon weeks.)

**Comment by chafey** [comment]
OK will try to update today.  It was highly reproducible for me with several different private keys - I was appending (new Date()).toString() to the message and it would fail ~25% of the time

**Comment by frankiebee** [comment]
@chafey what kind of accounts were they? Imported loose keys or were they accounts from your seed phrase?

**Comment by frankiebee** [comment]
also what were you signing can we get an exact copy of it?

**Comment by flyswatter** [comment]
Hi @chafey, sorry for the long delay, but I've found your issue.

First of all, it looks like you're checking for a prefixed signature, like geth and parity now use.  We are going to be adopting this feature, but first implementing it as `eth.personalSign`, and we are going to gradually deprecate the old `eth.sign` behavior, because it broke too many existing dapps to remove it abruptly.

This was probably confusing, because we did implement that new method for a day, but were met with a lot of broken Dapps, so we replaced it with a warning about the insecurity of eth.sign, while taking some time to implement the transition more smoothly.

I've added a loop of automated signature validations to our test suite, and so you should be able to use that method to recover a public key from a signature:

```javascript
web3.eth.sign(account, hashedData, function (err, sgn) {
          var r = ethUtil.toBuffer(sgn.slice(0,66))
          var s = ethUtil.toBuffer('0x' + sgn.slice(66,130))
          var v = ethUtil.bufferToInt(ethUtil.toBuffer('0x' + sgn.slice(130,132)))
          var m = ethUtil.toBuffer(msgHashHex)
          var pub = ethUtil.ecrecover(m, v, r, s)
          var adr = '0x' + ethUtil.pubToAddress(pub).toString('hex')
          if (adr !== account) throw new Error("I guess this doesn't fix it.")
          console.log("Ta-da!")
}
```

You can see some live examples of this [here](https://github.com/MetaMask/metamask-plugin/blob/0b0eec9c52667148fc69e1a3446bcd208dab3858/test/unit/keyrings/simple-test.js#L96).

Let me know if you have any other issues.  That code snippet should work for now, and we'll merge some subtle improvements immediately, and soon you'll be able to use `web3.eth.personalSign` for the prefixed style signing
