### ISSUE TITLE
Resetting password doesn't work

### ISSUE THREAD

**Issue by willnwhite** [MetaMask/metamask-plugin#1109]
Using the new password I get:

![screen shot 2017-02-10 at 11 41 34](https://cloud.githubusercontent.com/assets/8081877/22825792/0845c902-ef87-11e6-873f-245331468397.png)

**Comment by flyswatter** [comment]
Really sorry for this.  For the time being, uninstalling and reinstalling will solve your problem.

**Comment by willnwhite** [comment]
That worked, thanks.

**Comment by flyswatter** [comment]
One theory:
This could come from resetting a vault when an old vault exists, with a different password.
This would imply that on unlock, we're always unlocking both old and new.

Could be fixed by either:
- Clearing the old vault on vault reset/restore
- Not trying to unlock old vaults on unlock (not sure we do that, but it's a theory).

**Comment by flyswatter** [comment]
Addressed by #1181
