### ISSUE TITLE
Migrated vault cannot change password

### ISSUE THREAD

**Issue by Nogreedy** [MetaMask/metamask-plugin#1150]
Hello,
I want "only" to change my password.
I know my password and I know my seed.
I already tried to restore vault (I pressed "I forgot my password) and then I indicate my wallet seed and a new password. I have then access to my wallet... but when i exit from Metamask, if I want to access again, the new password doesn't work but it's again the old password to open my wallet...
Thanks in advance for your answer.

**Comment by Zanibas** [comment]
@Nogreedy when you exited MetaMask, did anything else happen? Did you manually lock it? Did MetaMask go through an update?

**Comment by flyswatter** [comment]
Hey @Nogreedy, we have a theory of what might be wrong, and to fix this (since you have your seed phrase already), try uninstalling and reinstalling metamask.  You should then be able to freely change your password.

**Comment by Nogreedy** [comment]
@Zanibas @flyswatter 
Thank you so much for your help.
I uninstalled and reinstalled Metamask... I indicated my wallet seed (import existing den) and when I enter a new password it **works now** perfectly. I think you can now close this issue....
Thanks.

**Comment by flyswatter** [comment]
I'll keep the issue open for now, because it represents a now known bug.

Our theory:

We recently migrated our encrypted vault formats.  When first unlocking your account, if you only had the old type of vault, it would migrate it to the new format.

It seems that a few things are wrong:
1. We don't destroy the old vault after migrating.
2. We continue validating the password against the old vault after the migration.
3. We do not update the old vault password when changing the password.

In combination, this means users whose vaults have auto-migrated cannot change their passwords.

Solutions to this can be simple.  Any one of these:
1. We destroy the old vault files (kept as an insurance policy)
2. We stop validating against the passwords when a new vault is present (this is the real bug)
3. We remove all the old vault logic entirely (we've been planning to do this soon anyway, and if we do it, that will also fix this problem.)

I'm going to rename this issue to reflect the current bug it represents.

**Comment by flyswatter** [comment]
Captured in #1181
