### ISSUE TITLE
Error returning event data

### ISSUE THREAD

**Issue by chejazi** [MetaMask/metamask-plugin#1324]
My browser is failing to retrieve event logs using Metamask. I created a test page that demonstrates this behavior at https://credsign.github.io/testnet/test.html

The error is as follows:
```
Error: Internal error
    at Object.InvalidResponse (inpage.js:6705)
    at inpage.js:6706
    at inpage.js:179
    at inpage.js:6682
```
It takes a long time (~1 minute) before the error is returned. Confirmed working in Mist.

**Comment by chejazi** [comment]
Also, figured I'd clarify that that test page targets data on the Ethereum main network, even though `testnet` is in the path.

**Comment by flyswatter** [comment]
This error is actually a Gateway timeout error, and I've added [a PR to Provider Engine to return better errors when this happens](https://github.com/MetaMask/provider-engine/pull/129).

You're querying the entire blockchain for logs.  This is an inappropriate use of logs. The request you are making is asking Infura to search every transaction in the history of the blockchain for events that match your query.

![screen shot 2017-04-17 at 1 30 12 pm](https://cloud.githubusercontent.com/assets/542863/25104770/809957d4-2376-11e7-8c8a-1499cd209f0d.png)

You should try querying for narrower rangers of blocks, instead of `0x0` to latest.

The new patch will give you an error message that looks more like this:

<img width="1000" alt="screen shot 2017-04-17 at 1 58 06 pm" src="https://cloud.githubusercontent.com/assets/542863/25104832/b34820de-2376-11e7-89d8-52d09674fe85.png">

Closing this for now, but the better error message will come out next time we release an updated version.
