### ISSUE TITLE
web3.version.getNetwork(cb)  doesn't call callback

### ISSUE THREAD

**Issue by Manidos** [MetaMask/metamask-plugin#1380]
Hey! Finally an easy-to-describe issue:
```
        web3.version.getNetwork((error, result) => {
          //never gets here
        });
```
As always, thank you for the amazing work!

**Comment by niktrix** [comment]
Cannot reproduce issus
Version Metamask 3.5.3

web3.version.getNetwork((error, result) => {
          console.log(result)
        });

returns my network id

**Comment by flyswatter** [comment]
@Manidos this sounds like the background process crashed.  Try switching the metamask network to something else and back again?

**Comment by Manidos** [comment]
@flyswatter, I'm sorry for not providing additional info. It must have been something on my end.  It now seems to be working just fine.

**Comment by micahalcorn** [comment]
I am experiencing this when MetaMask is trying to connect to a non-existent network. For example, if I have MM set to http://localhost:9545/ but I have forgotten to run `truffle develop`, then MM is constantly in a state of "Connecting to Unknown Private Network". The synchronous `web3.version.network` will return either `'loading'` or `null`, but the asynchronous `web3.version.getNetwork` will never call its callback. I am trying to avoid using the synchronous methods because of other side effects.

**Comment by Goodyearthai** [comment]
ขอรับค่าคอมมิสชั่นได้ทางไหนครับ

**Comment by danfinlay** [comment]
@micahalcorn Please open as a new issue.
