### ISSUE TITLE
Errors being dropped from response object

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#1488]
> deployment error: Error: Invalid JSON RPC response: {“id”:447,“jsonrpc”:“2.0”}

**Comment by flyswatter** [comment]
This is on `master`, not in production, right?  ie `3.7.0` but not `3.7.1`?

@Arachnid reported an error that sounds the same to me, the inpage provider seemed to be swallowing some errors instead of passing them to the DAPP.

`callback contain no result Gas required exceeds limit: 4689378`.

Good things to make sure work before we proceed.

**Comment by flyswatter** [comment]
The bug I listed was not the same bug, that was just a remix bug.

Forwarding the errors is probably missing from the new `stream subprovider`.

**Comment by michielmulders** [comment]
I got the same error with remix when deploying Guestbook.sol basic contract:
`callback contain no result Gas required exceeds limit: 4689378 `

Is there any solution?

**Comment by flyswatter** [comment]
Sorry @michielmulders, like I said in my last comment, this was not the same issue as we're discussing here. You're experiencing a bug that I believe [remix fixed 6 days ago](https://github.com/ethereum/remix/issues/506).  Do you need to pull latest from them?

**Comment by flyswatter** [comment]
Just to bring this thread back on track, this issue is about the `Stream Subprovider` not propagating errors correctly. I've actually [replaced the stream-provider in its place](https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/lib/inpage-provider.js#L2) at the moment, so this shouldn't be an issue.
