### ISSUE TITLE
Defaulting to Main Network

### ISSUE THREAD

**Issue by 2point1creations** [MetaMask/metamask-plugin#1553]
Hi MM Team,
We have alot of people in our gaming network now using MetaMask and the bulk of our support cases come from people who don't understand the difference between the Main Net and other Nets.  As a result noobies think they already have Ether in their wallet but then complain that our site is broken since all the functionality relates to the mainnet.   Is it possible to default MM to the mainnet so its less confusing to the non developer?

Thanks again.

**Comment by tmashuang** [comment]
We are still currently talking about it and have an open issue on this. Issue #1203.

**Comment by kumavis** [comment]
@2point1creations hello/
yes, we get a lot of support questions about this too.

defaulting to testnet is very intentional to indicate that we are in beta.
you must opt-in to using real ether on metamask.

this will change after we're satisfied with the safety of metamask.

some additional info here
https://github.com/MetaMask/metamask-plugin/pull/1208

**Comment by 2point1creations** [comment]
Awesome @kumavis 
I think we brought in the last week about 60 new users to MM and then our support team got flooded with that issue so we are writing a tutorial now explaining it.  MM is simply awesome and our clients love it so anything that makes it easier and better for the new user we are totally behind.  Again great work guys we wave the MM flag hard in our DApp :D

**Comment by flyswatter** [comment]
@2point1creations we have a little guide about it on [our faq](https://github.com/MetaMask/faq#q-i-just-imported-an-account-the-balance-is-wrong-wheres-my-eth).
