### ISSUE TITLE
Its 6th day and transaction is still stuck

### ISSUE THREAD

**Issue by vnandwana** [MetaMask/metamask-plugin#1578]
I used this plugin for the first time, for testing I transferred a small amount of ETH to MetaMask wallet. Wallet updated in no time. Then, I transferred the same amount back to another wallet but the other wallet never received the amount. It has already been 5 days and transaction is still stuck.

What options do I have here?

TxHash:    0xf3d9755f5b420f28b5b1fdfc50276f78ebae432c97409896dc8c9ab8430e64b3

Block Height:3832167 (26418 block confirmations)

TimeStamp: 5 days 43 mins ago (Jun-07-2017 01:01:37 AM +UTC)

From:  0x9465a67912d981d0be2e6beea0fc8b741ae0bc09

To:  0x35f305cac6caa15b922f3380586e55bba7327d2e
Value: 0.033359 Ether ($11.34) 
Gas Limit: 31500 
Gas Price: 0.000000022 
Ether Gas Used By Txn: 21000 
Actual Tx Cost/Fee: 0.000462 Ether ($0.16) 
Cumulative Gas Used: 3689883 
Nonce: 1

**Comment by flyswatter** [comment]
I recommend writing sooner when you have an issue, it should be impossible to submit a tx with metamask that takes more than an hour to get mined.

We have a guide on "unclogging" metamask, since we're aware of a few edge cases at the moment that we're working on:
https://github.com/MetaMask/faq/blob/master/USERS.md#slow-transactions
