### ISSUE TITLE
Seed not working

### ISSUE THREAD

**Issue by MagicMurry** [MetaMask/metamask-plugin#1614]
I've entered my seed in meta mask and it isn't allowing me to access my account.

**Comment by flyswatter** [comment]
First thing: would you try restarting your browser then trying again?

How old is your MetaMask installation? Have you had it for a long time?

**Comment by MagicMurry** [comment]
I installed it last Friday.


________________________________

**Comment by MagicMurry** [comment]
I removed the extension and reinstalled it. The purpose was for me to re enter my original seed phrase.

________________________________

**Comment by Zanibas** [comment]
Just to verify--your seed phrase is 12 words long, correct?

**Comment by MagicMurry** [comment]
correct

________________________________

**Comment by flyswatter** [comment]
You don't have to uninstall to restore from seed phrase. You can click "forgot my password" on the lock screen. (I know, not great wording)

**Comment by MagicMurry** [comment]
There's no option for that

________________________________

**Comment by MagicMurry** [comment]
There's a place to enter seed phrase and a new password

________________________________

**Comment by Zanibas** [comment]
Just to verify that it's a MetaMask issue rather than a problem with your seed phrase, could you test your seed word here:
https://www.myetherwallet.com/#send-transaction

Choose Mnemonic Phrase and simply see if the unlocking process works there. No need to actually send a transaction--just seeing the popup modal after pressing "unlock" should be enough. Don't send us a screenshot!

**Comment by MagicMurry** [comment]
Thank you all! I was able to retrieve my account. There was a word spelled incorrectly in the seed phrase.

**Comment by Zanibas** [comment]
Excellent! ^^
