### ISSUE TITLE
VERI not showing on MetaMask

### ISSUE THREAD

**Issue by jimiflynn13** [MetaMask/metamask-plugin#1638]

**Comment by tmashuang** [comment]
https://github.com/MetaMask/faq/blob/master/USERS.md#managing-tokens

**Comment by jimiflynn13** [comment]
Hi, I withdrew my 0.071 VERI from etherdelta to metamask.. the transactioned was comfirmed on etherscan but can't see it anywhere on metamask.... any idea wherew to look please?

**Comment by Zanibas** [comment]
If it's an incoming transaction, then the token will not appear on MetaMask, although we are in the middle of providing ways to see your token balances right now!

If the transaction indeed confirmed on etherscan and on https://ethplorer.io/, then you have nothing to worry about--again, MetaMask does not support displaying tokens yet, but expect this feature soon!

**Comment by jimiflynn13** [comment]
thank you.
why does my metamask balance show up on myetherwallet when i put in the mm address details? i thought they were seperate.

**Comment by Zanibas** [comment]
I assume you're using "View Wallet Info"?

The address that MetaMask provides you can be publicly examined by any block tracker, such as etherscan or myetherwallet. Separate addresses are separate accounts, but if you manage the same address with both MyEtherWallet and MetaMask, it's still the same account because it's the same address.

**Comment by jimiflynn13** [comment]
thats great thanks very much

**Comment by Zanibas** [comment]
If you have any other issues, let us know! =)
