### ISSUE TITLE
Allow creation and import of multiple wallet types

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#328]
## Current behavior

Right now MetaMask's wallet system is entirely BIP-44 seed-word based.

Whenever MetaMask is first set up, the user gets a twelve-word phrase, and it's used to generate their first account.

When restoring MetaMask, the only key-pairs you can import are ones derived from a BIP-44 compliant, twelve-word seed-word phrase like MetaMask uses at setup.

This means that when you press the `+` button under the account list, it always generates the same accounts in order.
## The problem

The ecosystem is full of alternative key signing methods, and we want the user to get to use one of their choosing.

For some users, it will be obvious that they want to import their old wallet file into MetaMask, not to mention it was a feature in [the original MetaMask preview](https://www.youtube.com/watch?v=A6PwkIneLXU).

Since our entire UX right now is designed around these twelve-word seed phrases, which are hard to explain to normal people,  there's a question of how to represent an account that is derived from your main seed words vs from a wallet file.
## Proposal: Organized vaults

The account list section could be divided into sections. A section would represent either a single key-pair wallet file, or a seed-word phrase.

The seed-word phrase sections would be unique, because they would have their own "add account" section.

<img width="374" alt="vault sections" src="https://cloud.githubusercontent.com/assets/542863/16361107/4f017c64-3b38-11e6-83a0-fea3e7f9058a.png">

Right now we're thinking these sub-sections would be views provided by that account type, so any features or UI elements that are specific to that keychain would show up in its collapsable section, or maybe it has an options gear button that navigates to a view it controls.

From this custom view, it could do as much interaction as it wanted, and then could pass it back to MetaMask when it was done.

**Comment by niran** [comment]
One idea is to draw a clear distinction between identities and the backups needed to recover them. This is similar to your mockups, except each identity would have an icon or label that indicates which backup is required for it. Instead of a Seed Vault section in the accounts list, each account tile would have something like ":closed_lock_with_key: 1". The geth wallet tile would have ":closed_lock_with_key: 2". There'd be another screen that lists backups with their names and creation or import dates. When you create a new identity, it tells you which backup is needed to recover it.

Another concept that would be nice to support is contract-based identities. Key-based identities are a dead-end because losing a key is too easy. Contract-based identities make it easier to design recovery strategies and use dapps with communal identities, like BoardRoom and multisig wallets.

With contract identity support, importing a seed or a wallet kicks off a registry lookup for any identities the key controls. Contract identities are typically created from a single factory, so it'd be easy to maintain an off-chain index of the identities each key controls. Once control of a contract identity changes, the factory is no longer a reliable source, but only BoardRoom currently allows that. Dapp UIs should record changes of control in a recovery registry to make it easy to see if a recovered key controls contract identities.

With backups conceptually separated from identities, there's nothing special about the UI for contract identities. It's just like another identity attached to a seed, and the recovery process is identical.

**Comment by nmushegian** [comment]
> With contract identity support, importing a seed or a wallet kicks off a registry lookup for any identities the key controls. Contract identities are typically created from a single factory, so it'd be easy to maintain an off-chain index of the identities each key controls. Once control of a contract identity changes, the factory is no longer a reliable source, but only BoardRoom currently allows that. Dapp UIs should record changes of control in a recovery registry to make it easy to see if a recovered key controls contract identities.

I don't think factories need to track ownership at all, you can just ask the contract itself for its history, since you know it is trustworthy because it came from the factory =]

**Comment by flyswatter** [comment]
New type of hardware wallet: https://www.ledgerwallet.com/products/12-ledger-nano-s

**Comment by flyswatter** [comment]
@VladTod if you have some free time, I'd appreciate you taking a visual pass on the above proposal.

The idea is that the account-list view is now a keychain-list view, and it has addable and collapsable keychains on it, which each can show whatever they want under them, usually a list of accounts, but also include details for adding new accounts.

**Comment by flyswatter** [comment]
I've begun a branch for working on this feature:
https://github.com/MetaMask/metamask-plugin/tree/i328-MultiVault

Its first commit is a document planning its architecture:
https://github.com/MetaMask/metamask-plugin/blob/i328-MultiVault/docs/multi_vault_planning.md

**Comment by flyswatter** [comment]
Tasks:
- [ ] Break up current functions' responsibilities to divide nicely along the new organization structure.
- [ ] Create tests for these newly discrete functions.
- [ ] Create idStore 2.0.
- [ ] Create Bip44Keychain module for backend.
- [ ] Ensure Bip44Keychain imports old format nicely.
- [ ] *UI* Separate vault (password encryption) creation from keychain (entropy) creation views.
- [ ] Organize Bip44KeychainComponent views into their own folder, isolate them organizationally into a `keychains` folder.
- [ ] Make places where Bip44KeychainComponent views are used agnostic to the type of KeychainComponent being used.

We will then have paved the way to theoretically easily:
- Add json-file account import Keychain module. #715
- Add uPort Keychain module. #716
- Add hardware (trezor or ledger) Keychain module. #605

**Comment by flyswatter** [comment]
Me and Kevin had a simplified MVP for this, that avoided many custom views, and uses a new tab for keychain creation.

The task list for that roadmap is this:

- [ ] Remove seed word confirmation code
- [ ] Create minimal KeychainManager & Bip44 keychain class (with init method)
- [ ] Define vault creation tab protocol
- [ ] Add BIP44 keychain creation page (for tab)
- [ ] That should do it, right?

Keychain.init {
	a method to digest the output of the new keychain tab.
}

Open questions:

What does init look like now?
	- Keep it simple, encourage a single type of vault by default?
	- Provide a list of options for first time users?
	- Hybrid? Encourage a obvious default, with a subtle advanced option?
	- uPort default?

**Comment by flyswatter** [comment]
We have some new designs in this issue's Quip designs folder.  I've assembled [a nearly comprehensive proposal](https://consensys.quip.com/qG1rAaKIDswa) for comments.

I'm starting to think that we actually *need* to make Keyring creation happen in a new tab, the benefits are just too considerable to ignore, so we could use design mockups for what an account creation browser page might look like.

It should have
- Metamask branding
- A security image
- Support for creating *or* importing.

This page could either be for a single Keyring type, or it could allow selecting keyrings within its UI, whatever we decide feels the most natural.

**Comment by flyswatter** [comment]
I'm now closing this as it's better represented with [a milestone](https://github.com/MetaMask/metamask-plugin/milestone/14).
