### ISSUE TITLE
Account Unlock Request > Proceed to unlocking

### ISSUE THREAD

**Issue by jorisbontje** [MetaMask/metamask-plugin#466]
When I get the "Account Unlock Request" notification, I'd like to be able to click on it to proceed to unlocking it.

Right now I need to dismiss it first by clicking on the X button (because it overlaps with my MetaMask icon, and just clicking on the notification itself doesn't dismiss it).

I would expect to be able to click on anywhere in the notification to dismiss it, and then get the MetaMask unlock panel.

**Comment by flyswatter** [comment]
There are two obstacles preventing us from implementing this right now:

1. The [WebExtensions Notifications API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications) does not support clicking the main body and performing an action, and we're using the WebExtension notification for this modal presently.
2. There is no WebExtension method to open our plugin programmatically, so we actually need a user to click the MetaMask icon to open the plugin.

I think there's a very viable solution in #452, where we entirely replace our use of WebExtension notifications with a new web window, which could have its own fully interactive content.

The dangerous piece would be if we put a password prompt in an arbitrary popup, and users became used to putting their passwords into arbitrary popups, it could become easier for an attacker to decrypt that user's account vault in the future via phishing.

This is not a full compromise, since the vault is still required, which is stored on the user's computer locally, but it still gives me pause.

One strategy many apps employ (like banking or medical apps) to give users confidence when typing a password into a new popup/window is to show something visual that a phisher would be unlikely to know. This is often in the form of a personal user photo that they selected on registration, but could be any image that is unique to the user that they recognize as theirs.

This couldn't just be their account identicon image, since we make the current account's address available to the current site, but we could consider generating a vault-global identicon that could be used to ensure that a dialog is coming from the user's own metamask instance.

So I think our options are these:
1. Do nothing, accept our fate as mediocre.
2. Replace notifications with popups, and add some kind of account-specific iconography to reduce the chances of entering the password in another site's popup, and then allow both unlocking and transaction approval from that same popup.

**Comment by flyswatter** [comment]
We **could** potentially add an unlock field right into the popup once we do #452, although there's now a trust issue of having users expect to type passwords into random popups, which could also be addressed by showing a unique image to the user to let them know it's metamask.

In the meantime, blocked by #452.

**Comment by kumavis** [comment]
We currently use popup windows instead of browser notifications.
Here is an issue for tracking the Security Image feature
https://github.com/MetaMask/metamask-plugin/issues/991
