### ISSUE TITLE
Unlock dialog remains after unlocking

### ISSUE THREAD

**Issue by jorisbontje** [MetaMask/metamask-plugin#467]
When I get a "Account Unlock Request" and proceed to unlock metamask, the unlock dialog remains even though the account is unlocked. I would expect to see the transaction that needs approval, or my account overview.

This seems to happen only the first time in a browser session where I have to Unlock metamask. When unlocking before an unlock request, or on subsequent unlocks (after manually locking) I get the confirmation panel as expected.

![image](https://cloud.githubusercontent.com/assets/620959/16980301/a35bc8ce-4e65-11e6-8071-2e44da67b36e.png)

**Comment by flyswatter** [comment]
This is a re-creation of #445, which I've never reproduced locally, but hoped had been fixed with the patch that closed it.

If you're able to reproduce this easily, it would help us a lot to get a state dump of the UI at this point (where you have the menu bar *and* the login screen, which should never happen). I just wrote up instructions on taking a state dump [here](https://github.com/MetaMask/metamask-plugin/blob/AddStateDumpInstructions/docs/state_dump.md). That would be really helpful, thanks!

**Comment by flyswatter** [comment]
Oh sorry @jorisbontje, actually we haven't pushed that fix to master yet!  It's possible this will be fixed with a simple version update, which I'll perform now.

**Comment by flyswatter** [comment]
Let us know if this is still happening in about an hour, when version `2.6.2` gets to you.

**Comment by jorisbontje** [comment]
Solved in 2.7.0
