### ISSUE TITLE
Sending ETH inside metamask triggers a notificattion

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#566]

**Comment by flyswatter** [comment]
Right now when we compose the background process's web3 provider, we assemble it with the Hooked Wallet Subprovider, which is what shows these notifications during any signing request, which is cool, because it means we literally never have code that would allow signing a tx without that user confirmation step.

To allow signing without a confirmation, we'll need to initialize a second web3 provider in the background, maybe composed out of the same original providers, but essentially creating an "unlocked & signing" provider.

We'll then have to make hooks for the popup UI to have access to this via its API, and expose those as React actions, and then use those actions from the send view instead of the direct web3 method like we do now.

A part of me has resisted calling this a bug, because adding an unlocked provider seems like a new security attack vector, but we'd never be injecting it into a website, so it's probably actually pretty benign.

**Comment by flyswatter** [comment]
This should be easier than ever to fix, because all we should have to do is add a check:

Before opening a popup, check if the `popup.html` window is currently open. If it is, we don't need to create a new window.

**Comment by flyswatter** [comment]
This looks so much worse on a Debian system!  The popup is a full size window, it's awful. It's so redundant, raising the priority on this.
