### ISSUE TITLE
Gas estimation bug

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#60]
I started writing a blog post on truffle + metamask, but hit a snag where truffle via RPC could send this contract's transactions, but MetaMask couldn't. I'm talking out of the box `truffle init` dapp not working with Metamask.

The RPC returns to metamask this error:

```
Error: Error: VM Exception while executing transaction: out of gas(…)
```

You can trace my footsteps [following this draft of the blog post](https://gist.github.com/flyswatter/aea93752fb90322bbe11).

@kumavis

**Comment by gamarin2** [comment]
Very similar issue, it seems that sending the entire balance of token from an account to another throws the following error : 
`Error: Error: VM Exception while executing transaction: out of gas(…)`

It happens with the default truffle Metacoin contract https://github.com/ConsenSys/truffle/blob/master/example/contracts/MetaCoin.sol
and with any ERC 20 Standard Token https://github.com/ConsenSys/Tokens/blob/master/Token_Contracts/contracts/StandardToken.sol.

For example, if the balance of accounts[0] is 100 meta, sending 99 meta is fine but 100 throws the error. Both transaction work fine with truffle + testrpc, the error occurs with Metamask only.

Sidenote : Since the previous issue seemed to have something to do with gas estimation, I add that some other (more elaborate) functions that work fine with truffle + testRPC throw the following Error within Metamask : 
`Error: Error: VM Exception while executing eth_estimateGas: invalid JUMP(…)`

**Comment by kumavis** [comment]
`eth_estimateGas` is not performed by MetaMask, its handled by the rpc client. More likely this is an issue in testrpc/provider-engine.

**Comment by kumavis** [comment]
> how does mist autofill tx gasLimit ?
> Running estimate gas and then adding 100000

**Comment by flyswatter** [comment]
Closing in favor of #738
