### ISSUE TITLE
Remove stack trace from error messages.

### ISSUE THREAD

**Issue by nanexcool** [MetaMask/metamask-plugin#672]
When you cancel a transaction or an error happens, the error returned by MetaMask has the error message on the first line, and the whole stacktrace on subsequent lines. Might be better to have just the first line on `error.message` and the rest on `error.stackTrace`.

Currently if we do `error.toString()` for MetaMask we have to discard everything after the first line otherwise we can't just show that in our UI.

**Comment by Zanibas** [comment]
I've picked this up, but could I get some clarification on what you're expecting? Perhaps I'm  not understanding what needs to be different with our error messages, since they seem to produce the behavior you're expecting. Am I not looking at the same errors as you are?

Some screenshots may help! Thanks!

**Comment by flyswatter** [comment]
I think #756 is a good expression of this problem.

Right now though, it does look like we're trying to only log `error.message`, so I'm inclined to think that something in the stack is concatenating the stack trace, which is why I asked chevdor to log the state over there.

**Comment by Zanibas** [comment]
I believe this issue is closed for now with the fix from #811. Someone re-open this if this is not the case!
