### ISSUE TITLE
Allow for ICAP addresses

### ISSUE THREAD

**Issue by mcgravier** [MetaMask/metamask-plugin#685]
Some mobile wallets (like Jaxx) are using ICAP
https://github.com/ethereum/wiki/wiki/ICAP:-Inter-exchange-Client-Address-Protocol
in QR codes instead of regular addreses. This creates issues when trying to scan QR code with webcam and paste that addres to metamask since it does not allow ICAP format

**Comment by flyswatter** [comment]
This looks interesting, could you expand on how you'd imagine this feature working?

Would every address input field need to check for the format being pasted?

When copying an address in MetaMask, would you like the option of copying an ICAP address?

Would you like MetaMask's QR code to be in the ICAP format?

Any other descriptions of how you'd like this feature implemented would be appreciated, since I haven't seen any need for this feature yet, and am curious how you'd hope to use it.

**Comment by mcgravier** [comment]
I think, that in case of Jaxx, using different address format for QR, and different one displaying on phone screen, is plain bad practice - nevertheless, we can expect similar things from other software and so, we have to deal with it.

> Would every address input field need to check for the format being pasted?

Since it is nice to be able to double chceck that pasted address matches the one on my phone, It should check the format, and also display address in other form - so if I paste ICAP, I can see regular version as well  

> Would you like MetaMask's QR code to be in the ICAP format?

No. All wallet software accepts regular addresses, but some may not accept ICAP - for this reason I'd prefer to stay with regular format - at least for now.

> Any other descriptions of how you'd like this feature implemented would be appreciated, since I haven't seen any need for this feature yet, and am curious how you'd hope to use it.

I'd like this to be implemented along with webcam support  #686  - so user can easly move funds from any phone wallet to MetaMask, without use of external QR scanning software

**Comment by flyswatter** [comment]
Closing as a subset of #686
