### ISSUE TITLE
Warn that keys will be lost before removing chrome plugin

### ISSUE THREAD

**Issue by yaronvel** [MetaMask/metamask-plugin#703]
I just removed my metamask chrome plugin in order to upgrade it. But I realized my account might be deleted now. Is there a way to restore them (getting the private keys is enough) before I re-install?

**Comment by flyswatter** [comment]
Hi @yaronvel,

First, if you wrote down your twelve word seed phrase, that's all you need, we try to warn people to keep that phrase because there's not much else to do from there.

That said, you could also check to see if maybe the localstorage files haven't been deleted yet.
http://superuser.com/questions/507536/where-does-google-chrome-save-localstorage-from-extensions

And if it has been deleted, you could pursue options to restore it, like TimeMachine on a Mac, or some other drive recovery software.

I don't know how hard you want to try, since I don't know how much you stored in this account, but those are your options.

**Comment by flyswatter** [comment]
The WebExtension API doesn't really provide a way to prevent a user from uninstalling the extension, it's up to the user to do.

There is an API to give us one brief moment of cleanup, I guess we could `alert` the user with their wallet or something.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Runtime/onSuspend#Browser_compatibility

To help avoid others from making this mistake, could you tell us, what made you think you needed to uninstall to update?  Was it our slack announcement's wording?

Did you have any luck recovering?

**Comment by yaronvel** [comment]
First of all thank you for the support.
I did had record for some of my private keys in some python code I wrote, so over all I lost only 1 ether, which is not too bad.

I didn't see any update button, so I thought the sure thing was to uninstall and re-install.

On a related issue, it would also be nice if there were a disable option for metamask.
During development I sometimes want to switch to RPC client. So far, I had to uninstall the plugin to do it, which was not so bad as I had only test ether there. But as the app went live I also need to hold real ether.

**Comment by flyswatter** [comment]
You can disable any plugin by right clicking it, selecting “Manage extensions”, and unchecking the box next to it that says “enabled”.

**Comment by flyswatter** [comment]
For the record, MetaMask auto-updates, so you shouldn't ever have to uninstall it.

Glad you got most of your ether back!  Closing this now.

**Comment by hannesH63** [comment]
@danfinlay you mentioned it can be possible to restore metamask plugin from local files. The link you posted doesn't really help me. I already found the local file storage from chrome. But how is it possible to use these files? or restore the previous version of the plugin. I only have my password. Not the 12 word pass phrase. I don't know, i just have the pw. Is it possible to get to the UTC keystore file in any way? I could reopen the wallet with mew then, because i have the pw. 

Thanks in advance.

greetings

**Comment by danfinlay** [comment]
MetaMask does not store in the UTC keystore format, so you have to look for our JSON local storage location, and from there you can extract your seed phrase using your password with [this online tool](https://metamask.github.io/vault-decryptor/).
