### ISSUE TITLE
Auto re-submit transactions until confirmed

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#825]
We've been getting a lot of reports of transactions not reaching the blockchain.

This has largely been due to our RPC client backends being updated frequently for the frequent hard forks, which in turn means these clients are less stable, and more prone to corrupting or failing in unexpected ways.

While Infura is [building infrastructure](https://github.com/INFURA/infura/issues/5) to queue & retry transactions on their end, we should build this robustness at all layers of the stack, and MetaMask should also handle the automatic resubmission of transactions, in case there are snags on its backend.

Off the cuff, I figure re-submitting a tx every 5 seconds until we have a confirmation would be reasonable, with a 2 minute upper limit should be more than enough to ensure inclusion in the blockchain.

**Comment by flyswatter** [comment]
Will fix #760

**Comment by rolandkofler** [comment]
This transaction does not reach the network. 
Before I was able to disable/enable the extention to make it work again (could be a connection drop) but since I switched to mainnet this workaround doesn't work either. 

![image](https://cloud.githubusercontent.com/assets/979444/20454192/5bb0d21a-ae39-11e6-8282-cd6a2369c351.png)

https://etherscan.io/tx/0x1e63a97683de6ef9cf72f7a0bbaaebdf00fd18c76facbf8a72f8403bff748d6c

**Comment by rolandkofler** [comment]
On the same machine, JAXX works

**Comment by flyswatter** [comment]
Closing since this is a solution, not a problem, and we have the problem open in a few other issues.
