### ISSUE TITLE
Host notifications via GitHub

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#934]
transparency
git history
less infrastructure

👍 👍 👍

**Comment by Zanibas** [comment]
My initial investigations have come up as such:

While hosting our notifications via GitHub could potentially be viable, we are currently limited by either rate limiting or the fact that we are a purely public-facing application without any 'servers' of our own to initiate OAUTH.

GitHub allows for 60 requests/hour for unauthenticated requests. This would mean using one request to get a list of notices, and then one request for each notice's binary to be loaded in. While this should work in a majority of cases, it may mess up people's use of GitHub if they end up using unauthenticated requests for other applications, or in rare cases, due to rapid installation/uninstallation, that limit may get maxed out. Again, 99% of users won't ever be affected, but there is this 1% that we can never really fix.

If we move to authenticated requests (5000/hr), there are some problems here with OAuth or any other authentication scheme. It requires a GitHub login as well as secret keys that we can't just leave hanging in our client-side app. We would need a centralized server to dish out OAuth tokens. 

So while we have a feasible way of doing this, there really isn't an elegant solution here to handle that 1% without moving to a centralized server with login clunk. If we were going to make a server, we might as well just make our own API for serving notices, but this goes against transparency, history, and creates more infrastructure to maintain.

**Comment by Zanibas** [comment]
Since nobody has really addressed these concerns, I'm considering this closed for now. We can always host notifications via an API on a server we own. Sure, less transparent, but we're limited by our chrome extension for now.
