### ISSUE TITLE
if you switch from testnet to localhost even though you dont have a node running it locks you out and you cant log back in

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#946]
reproduction steps: 
- switch network to localhost...
- try to unlock account 

you will get a err for wrong password

**Comment by flyswatter** [comment]
I take it this is on `dev` branch?

**Comment by frankiebee** [comment]
yes

**Comment by flyswatter** [comment]
Dev branch issues should go into the Multi-Vault milestone, since they don't affect what's in production.

**Comment by flyswatter** [comment]
I think I'm working on this issue right now.

**Comment by flyswatter** [comment]
I think my new passworder managed to break things :(

**Comment by flyswatter** [comment]
Oh, I should make this an announcement to you and all @MetaMask/devs

This regards anyone who has been building their own copy of MetaMask, and is using a build that is less than 2 months old.  If you haven't pulled the `dev` branch yet, this doesn't affect you.

We've changed our strategy for password-encryption on the `dev` branch in the `2.x.x` version bump of [browser-passworder](https://www.npmjs.com/package/browser-passworder).  That module now represents MetaMask's disk encryption strategy.

The new version does 10k loops of hashing on the password data before deriving a private key, with its salt and vector. Should be considerably harder to brute-force crack a metamask vault now, even with physical access.

The result is, you may pull and build a recent commit of MetaMask, (and `npm install`), and suddenly find you can't decrypt your vault anymore.  This will require a reinstallation & restore of your dev build.

One nice way to isolate these concerns in the future, is do what I do, I have a main (chrome-installed) copy of MetaMask, with some accounts with real ether in them, but I keep it usually disabled in the chrome menu, because I usually have my local dev build enabled instead, with its own seed phrase and testnet tokens.

When I want to do something with my stable accounts, I just swap which MetaMask is enabled. 

Anyways, I'm closing the issue, because it shouldn't affect anyone in the future. I've written a thorough explanation just in case any other devs are building locally, we can point them here.
